name: Github Actions With Docker Containers
on:
  push:
    branches:
      - main
env:
  CACHE_KEY: node-deps
  MONGODB_NAME: gha-docker-demo
jobs:
  test:
    runs-on: 'macos-latest'
    environment: testing
    env:
      MONGODB_PROTOCOL: mongodb+srv
      MONGODB_ADDRESS: cluster0.ierxn0t.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    steps:
      - name: Get the Code.
        uses: actions/checkout@v5
      - name: Install all the dependencies.
        run: npm install
      - name: Install all dependencies with sanity.
        run: npm ci
      - name: Create the update npm cache.
        uses: actions/upload-artifact@v4
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run the server.
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run Tests.
        run: npm run test
      - name: Output the github logs.
        run: |
          echo {{ toJSON(github) }}
          echo "MONGODB_USERNAME: "${{MONGODB_USERNAME}}""
      - name: Finish Test
        run: echo "Successfully Finished the Test Job."
  deploy:
    needs: test
    runs-on: 'macos-latest'
    steps:
      - name: Output information.
        env: 
          PORT: 3000
        run: |
          echo "MONGODB_NAME: "${{ MONGODB_NAME }}""
          echo "MONGODB_USERNAME: "${{ MONGODB_USERNAME }}""
          echo "${{ env.PORT }}"