name: Github Actions With Docker Containers
on:
  push:
    branches:
      - main
env:
  CACHE_KEY: node-deps
  MONGODB_NAME: github-actions-docker-container
jobs:
  test:
    runs-on: 'ubuntu-latest'
    environment: testing
    container:
      image: node:18
      env:
        MONGODB_PROTOCOL: mongodb
        MONGODB_ADDRESS: 127.0.0.1:27017
        MONGODB_USERNAME: root
        MONGODB_PASSWORD: example
        PORT: 8080
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - name: Get the Code.
        uses: actions/checkout@v5
      - name: Create the update npm cache.
        id: npm-cache-test
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install all dependencies with sanity.
        run: npm ci
      - name: Run the server.
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run Tests.
        run: npm test
      - name: Output the github logs.
        run: |
          echo {{ toJSON(github) }}
          echo "MONGODB_USERNAME: "$MONGODB_USERNAME"
      - name: Finish Test
        run: echo "Successfully Finished the Test Job."
  deploy:
    needs: test
    runs-on: 'ubuntu-latest'
    container:
      image: node:18
    steps:
      - name: Output information.
        env: 
          PORT: 3000
        run: |
          echo "MONGODB_NAME: "$MONGODB_NAME""
          echo "MONGODB_USERNAME: "$MONGODB_USERNAME"
          echo "${{ env.PORT }}"